name: profunctor-instance
version: 0.0.0

ghc-options: -Wall -Werror

default-extensions:
- ApplicativeDo
- BlockArguments
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- LambdaCase
- NamedFieldPuns
- OverloadedStrings
- PatternSynonyms
- QuasiQuotes
- RecordWildCards
- ScopedTypeVariables
- TypeApplications
- ViewPatterns

dependencies:
- base
- profunctors

library:
  source-dirs: src