name: free-lattice-product
version: 0.0.0

ghc-options: -Wall -Werror

default-extensions:
- ApplicativeDo
- BlockArguments
- FlexibleContexts
- FlexibleInstances
- GADTs
- GeneralizedNewtypeDeriving
- ImportQualifiedPost
- LambdaCase
- NamedFieldPuns
- OverloadedStrings
- PatternSynonyms
- QuasiQuotes
- RecordWildCards
- ScopedTypeVariables
- TypeApplications
- TypeFamilies
- ViewPatterns

dependencies:
- base
- containers
- nonempty-containers

library:
  source-dirs: src